<?php

namespace CDC\ChartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StudyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudyRepository extends EntityRepository
{
}
