INSERT INTO Study VALUES('', 'YRBSS', 'Youth Risk Behavior Surveillance System', 'CDC.gov');

INSERT INTO Category Values('1', 'Unintentional Injuries and Violence', '', '1');
INSERT INTO Category Values('2', 'Tobacco Use', '', '1');
INSERT INTO Category Values('3', 'Alcohol and Other Drug Use', '', '1');
INSERT INTO Category Values('4', 'Sexual Behaviors', '', '1');
INSERT INTO Category Values('5', 'Dietary Behaviors', '', '1');
INSERT INTO Category Values('6', 'Physical Activity', '', '1');
INSERT INTO Category Values('7', 'Asthma', '', '1');

INSERT INTO Question VALUES('', 'Wore a Bicycle Helmet', 'Students who had ridden a bicycle rarely wore or never wore a bicycle helmet during the 12 months before the survey. ', '1');
INSERT INTO Question VALUES('', 'Wore a Seat Belt', 'Students rarely wore or never wore a seatbelt when riding a car driven by someone else. ', '1');
INSERT INTO Question VALUES('', 'Drunk Driving-Passenger', 'Students rode one or more times in a car or other vehicle with a driver who had been drinking alcohol during the 30 days before the survey. ', '1');
INSERT INTO Question VALUES('', 'Drunk Driving-Driver', 'Students drove a car or other vehicle once or multiple times while they were drinking alcohol during the 30 days before the survey.', '1');
INSERT INTO Question VALUES('', 'Carried Weapon at School', 'Students carried a weapon on school property at least one day during the 30 days before the survey. ', '1');
INSERT INTO Question VALUES('', 'Did Not Go to School ', 'Students did not go to school because they felt unsafe at school or on their way to or from school on at least 1 day in the 30 days before the survey.', '1');
INSERT INTO Question VALUES('', 'Threatened or injured', 'Students were threatened or injured with a weapon (such as a gun, knife, or club) on school property one or more times during the 12 months before the survey. ', '1');
INSERT INTO Question VALUES('', 'Fought at School', 'Students were in a physical fight one or more times on school property in the 12 months before the survey.', '1');
INSERT INTO Question VALUES('', 'Bullied in School', 'Students were bullied on school property in the 12 months before the survey. ', '1');
INSERT INTO Question VALUES('', 'Felt Sad', 'Students felt sad or hopeless almost every day for 2 or more weeks in a row so that they stopped doing some usual activities during the 12 months before the survey. ', '1');
INSERT INTO Question VALUES('', 'Considered Suicide', 'Students attempted suicide one or more times during the 12 months before the survey. ', '1');
INSERT INTO Question VALUES('', 'Planned Suicide', 'Students made a plan about how they would attempt suicide during the 12 months before the survey. ', '1');
INSERT INTO Question VALUES('', 'Attempted Suicide', 'Students attempted suicide one or more times during the 12 months before the survey. ', '1');
INSERT INTO Question VALUES('', 'Suicide Attempt Treated', 'Students attempted suicide which resulted in an injury, poisoning, or overdose that had to be treated by a doctor or nurse during the 12 months before the survey.', '1');
INSERT INTO Question VALUES('', 'Carried Weapon', 'Students carried a weapon such as a gun, knife, or club on at least one day during the 30 days before the survey. ', '1');
INSERT INTO Question VALUES('', 'Carried Gun', 'Students carried a gun on at least one day during the 30 days before the survey.', '1');
INSERT INTO Question VALUES('', 'Physical Fight', 'Students were in a physical fight one or more times during the 12 months before the survey.', '1');
INSERT INTO Question VALUES('', 'Injured in Fight', 'Students were injured in a physical fight one or more times and the injury had to be treated by a doctor or nurse during the 12 months before the survey.', '1');
INSERT INTO Question VALUES('', 'Experienced Dating Violence', 'Students were hit, slapped, or physically hurt on purpose by their girlfriend or boyfriend during the 12 months before the survey. ', '1');
INSERT INTO Question VALUES('', 'Forced to Have Sex', 'Students were physically forced to have sexual intercourse when they did not want to. ', '1');
INSERT INTO Question VALUES('', 'Bullied Electronically', 'Students were electronically bullied through e-mail, chat rooms, instant messaging, web sites, or texting during the 12 months before the survey. ', '1');
INSERT INTO Question VALUES('', 'Ever Smoked Cigarettes', 'Students who ever tried smoking a cigarette, even just one or two puffs.', '2');
INSERT INTO Question VALUES('', 'Smoked Before 13', 'Students who smoked a whole cigarette for the first time before the age of 13. ', '2');
INSERT INTO Question VALUES('', 'Currently Smokes Cigarettes', 'Students smoked cigarettes on at least one day during the 30 days before the survey.', '2');
INSERT INTO Question VALUES('', 'Frequently Smokes Cigarettes', 'Students smoked cigarettes on 20 or more days during the 30 days before the survey. ', '2');
INSERT INTO Question VALUES('', 'Daily Smoker', 'Students who currently smoked cigarettes smoked 10 or more cigarettes per day during the 30 days before the survey.', '2');
INSERT INTO Question VALUES('', 'Smoked at School', 'Students smoked cigarettes on school property on at least 1 day during the 30 days before the survey.  ', '2');
INSERT INTO Question VALUES('', 'Occassional Smoker', 'Students who ever smoked at least one cigarette every day for 30 days. ', '2');
INSERT INTO Question VALUES('', 'Quit Smoking', 'Students who currently smoked cigarettes did not try to quit smoking in the 12 months before the survey.', '2');
INSERT INTO Question VALUES('', 'Bought Cigarettes', 'Students who were younger than 18 years and currently smoked usually obtained their own cigarettes by buying them in a store or gas station during the 30 days before the survey.', '2');
INSERT INTO Question VALUES('', 'Used Smokeless Tobacco', 'Students used chewing tobacco, snuff, or dip on at least 1 day during the 30 days before the survey. ', '2');
INSERT INTO Question VALUES('', 'Used Dip/Snuff at School', 'Students used chewing tobacco, snuff, or dip on school property on at least 1 day during the 30 days before the survey. ', '2');
INSERT INTO Question VALUES('', 'Smokes Cigars', 'Students smoked cigars, cigarillos, or little cigars on at least 1 day during the 30 days before the survey.  ', '2');
INSERT INTO Question VALUES('', 'Uses Any Tobacco', 'Students smoked cigarettes, cigars, cigarillos, little cigars, or used chewing tobacco, snuff, or dip on at least one day during the 30 days before the survey ', '2');
INSERT INTO Question VALUES('', 'Ever Drank Alcohol', 'Students ever had at least one drink of alcohol at least 1 day in their life.', '3');
INSERT INTO Question VALUES('', 'Alcohol Before 13', 'Students drank alcohol, other than a few sips, for the first time before age 13 years. ', '3');
INSERT INTO Question VALUES('', 'Recently Drank Alcohol', 'Students had at least one drink of alcohol on at least 1 day during the 30 days before the survey. ', '3');
INSERT INTO Question VALUES('', 'Binge Drinking', 'Students had five or more drinks of alcohol in a row within a couple of hours on at least 1 day during the 30 days before the survey.', '3');
INSERT INTO Question VALUES('', 'Given Alcohol', 'Students who currently drank alcohol, usually obtained the alcohol they drank by someone giving it to them during the 30 days before the survey. ', '3');
INSERT INTO Question VALUES('', 'Drank Alcohol at School', 'Students had at least one drink of alcohol on school property on at least one day during the 30 days before the survey. ', '3');
INSERT INTO Question VALUES('', 'Used Marijuana', 'Students who ever used marijuana one or more times during their life. ', '3');
INSERT INTO Question VALUES('', 'Used Marijuana Before 13', 'Students who tried marijuana for the first time before the age of 13. ', '3');
INSERT INTO Question VALUES('', 'Currently Uses Marijuana ', 'Students used marijuana one or more times during the 30 days before the survey.', '3');
INSERT INTO Question VALUES('', 'Uses Marijuana at School', 'Students used marijuana on school property one or more times during the 30 days before the survey. ', '3');
INSERT INTO Question VALUES('', 'Ever Used Cocaine', 'Students who ever used any form of cocaine, such as powder, crack, or freebase during their life one or more times.', '3');
INSERT INTO Question VALUES('', 'Used Cocaine Recently', 'Students who ever used any form of cocaine, such as powder, crack, or freebase during the 30 days before the survey.', '3');
INSERT INTO Question VALUES('', 'Ever Used Inhalants', 'Students who ever sniffed glue, breathed the contents of aerosol spray cans, or inhaled any paints or sprays to get high one or more times during their life. ', '3');
INSERT INTO Question VALUES('', 'Ever Used Heroin', 'Students who have ever used heroin (also called smack, junk, or China white) one or more times during their life. ', '3');
INSERT INTO Question VALUES('', 'Ever Used Methamphetamines', 'Students who have ever used methamphetamines (also called speed, crystal, or ice) one or more times during their life. ', '3');
INSERT INTO Question VALUES('', 'Ever Used Ecstasy', 'Students who have ever used ecstasy (also called MDMA) one or more times during their life.', '3');
INSERT INTO Question VALUES('', 'Ever Used Steroids', 'Students who ever took steroid pills or shots without a doctor’s prescription one or more times during their life.', '3');
INSERT INTO Question VALUES('', 'Ever Used Prescription Drugs', 'Students used prescription drugs such as Oxycontin, Percocet, Vicodin, codeine, Adderall, Ritalin, or Xanax without a doctor’s prescription one or more times during their life. ', '3');
INSERT INTO Question VALUES('', 'Ever Injected Drugs', 'Students ever used a needle to inject any illegal drug into their body one or more times during their life. ', '3');
INSERT INTO Question VALUES('', 'Drug Transactions at School', 'Students who were offered, sold, or given an illegal drug by someone on school property during the 12 months before the survey. ', '3');
INSERT INTO Question VALUES('', 'Sexual Intercourse', 'Students who ever had sexual intercourse.', '4');
INSERT INTO Question VALUES('', 'Sexual Intercourse Before 13', 'Students who had sexual intercourse for the first time before the age of 13. ', '4');
INSERT INTO Question VALUES('', 'Sex with Four or More Partners', 'Students who had sexual intercourse with four or more persons during their life. ', '4');
INSERT INTO Question VALUES('', 'Sexual Intercourse Recently', 'Students had sexual intercouse with at least one person during the 3 months before the survey.  ', '4');
INSERT INTO Question VALUES('', 'Substance Use Before Sex', 'Students who were currently sexually active drank alcohol or used drugs before last sexual intercourse.', '4');
INSERT INTO Question VALUES('', 'No Condom Use ', 'Students who were currently sexually active did not use a condom during last sexual intercourse.', '4');
INSERT INTO Question VALUES('', 'No Birth Control Pill Use', 'Students who were currently sexually active did not use birth control pills before last sexual intercourse to prevent pregnancy. ', '4');
INSERT INTO Question VALUES('', 'No AIDS or HIV Education', 'Students who were never taught in school about AIDS or HIV infection.', '4');
INSERT INTO Question VALUES('', 'Did Not Use a LARC Method', 'Students who were currently sexually active did not use Long-Acting, Reversible Contraception (LARC) such as Depo-Provera (or any injectable birth control), Nuva Ring (or any birth control ring), implanon (or any implant), or any IUD use before last sexual intercourse to prevent pregnancy. ', '4');
INSERT INTO Question VALUES('', 'Did Not Use Birth Contol Pills or LARC', 'Students who were currently sexually active did not use birth control pills or Long-Acting, Reversible Contraception (LARC) such as Depo-Provera (or any injectable birth control), Nuva Ring (or any birth control ring), implanon (or any implant), or any IUD before last sexual intercourse to prevent pregnancy. ', '4');
INSERT INTO Question VALUES('', 'Did Not Use Dual Methods of Birth Control', 'Students who were currently sexually active did not use both a condom during last sexual intercourse and birth control pills or Depo-Provera (or any injectable birth control), Nuva Ring (or any birth control ring), implanon (or any implant), or any IUD before last sexual intercourse to prevent pregnancy.', '4');
INSERT INTO Question VALUES('', 'Did Not Use Any Birth Control', 'Students who were currently sexually active did not use any method to prevent pregnancy during last sexual intercourse. ', '4');
INSERT INTO Question VALUES('', 'Did Not Drink Fruit Juice', 'Students did not drink 100% fruit juices during the 7 days before the survey.', '5');
INSERT INTO Question VALUES('', 'Did Not Eat Fruit', 'Students did not eat fruit during the 7 days before the survey.', '5');
INSERT INTO Question VALUES('', 'Did Not Eat Green Salad', 'Students did not eat a green salad during the 7 days before the survey.', '5');
INSERT INTO Question VALUES('', 'Did Not Eat Potatoes', 'Students did not eat potatoes during the 7 days before the survey.', '5');
INSERT INTO Question VALUES('', 'Did Not Eat Carrots', 'Students did not eat carrots during the 7 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Did Not Eat Other Vegetables', 'Students did not eat other vegetables (excluding green salad, potatoes, or carrots) during the 7 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Drank Soda Recently', 'Students drank a can, bottle, or glass of soda or pop (excluding diet soda or diet pop) during the 7 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Drank One or More Sodas a Day', 'Students drank a can, bottle, or glass of soda or pop (excluding diet soda or diet pop) one or more times per day during the 7 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Drank Two or More Sodas a Day', 'Students drank a can, bottle, or glass of soda or pop (excluding diet soda or diet pop) two or more times per day during the 7 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Drank Three or More Sodas a Day', 'Students drank a can, bottle, or glass of soda or pop (excluding diet soda or diet pop) three or more times per day during the 7 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Did Not Eat Fruit or Drink Fruit Juice', 'Students did not eat fruit or drink 100% fruit juices during the 7 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Ate Fruit Less Than Once a Day', 'Students ate fruit or drank 100% fruit juices less than one time per day during the 7 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Ate Fruit Less Than Twice a Day', 'Students ate fruit or drank 100% fruit juices less than two times per day during the 7 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Ate Fruit Less Than Three Times a Day', 'Students ate fruit or drank 100% fruit juices less than three times per day during the 7 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Did Not Eat Vegetables', 'Students did not eat vegetables like green salad, potatoes (excluding French fries, fried potatoes, or potato chips), carrots, or other vegetables during the 7 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Ate Vegetables Less Than Once a Day', 'Students ate vegetables like green salad, potatoes (excluding French fries, fried potatoes, or potato chips), carrots, or other vegetables less than one time per day during the 7 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Ate Vegetables Less Than Twice a Day', 'Students ate vegetables like green salad, potatoes (excluding French fries, fried potatoes, or potato chips), carrots, or other vegetables less than two times per day during the 7 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Ate Vegetables Less Than Three Times a Day', 'Students ate vegetables like green salad, potatoes (excluding French fries, fried potatoes, or potato chips), carrots, or other vegetables less than three times per day during the 7 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Overweight ', 'Students who were greater than or equal to the 85th percentile but less than the 95th percentile for body mass index, based on sex\- and age\-specific reference data from the 2000 CDC growth charts. ', '5');
INSERT INTO Question VALUES('', 'Obese', 'Students who were greater than or equal to the 95th percentile for body mass index, based on sex- and age-specific reference data from the 2000 CDC growth charts.', '5');
INSERT INTO Question VALUES('', 'Self-Identified as Overweight', 'Students who described themselves as slightly or very overweight. ', '5');
INSERT INTO Question VALUES('', 'Did Not Eat', 'Students who fasted for 24 or more hours to lose weight or to keep from gaining weight during the 30 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Took Pills to Lose Weight', 'Students who took diet pills, powders, or liquids to lose weight or to keep from gaining weight without a doctor’s advice during the 30 days before the survey.', '5');
INSERT INTO Question VALUES('', 'Vomited to Lose Weight', 'Students who vomited or took laxatives to lose weight or to keep from gaining weight during the 30 days before the survey. ', '5');
INSERT INTO Question VALUES('', 'Moderately Physically Active', 'Students who were physically active at least 60 minutes per day on less than 5 days doing any kind of physical activity that increased their heart rate and made them breathe hard some of the time during the 7 days before the survey. ', '6');
INSERT INTO Question VALUES('', 'No Physical Education Classes', 'Students did not attend physical education classes in an average week when they were in school. ', '6');
INSERT INTO Question VALUES('', 'Regular Physical Education Classes', 'Students did not attend physical education classes 5 days in an average week when they were in school. ', '6');
INSERT INTO Question VALUES('', 'Does Not Play Sports', 'Students did not play on sports teams run by their school or community groups during the 12 months before the survey.', '6');
INSERT INTO Question VALUES('', 'Watches Television Excessively', 'Students watched television 3 or more hours per day on an average school day. ', '6');
INSERT INTO Question VALUES('', 'Plays Computer Excessively', 'Students used computers 3 or more hours per day playing video or computer games or used a computer for something that was not school work on an average school day. ', '6');
INSERT INTO Question VALUES('', 'Physically Active', 'Students are physically active at least 60 minutes per day on less than 7 days doing any kind of physical activity that increased their heart rate and made them breathe hard some of the time during the 7 days before the survey. ', '6');
INSERT INTO Question VALUES('', 'Not Physically Active', 'Students did not participate in at least 60 minutes of physical activity on any day doing any kind of physical activity that increased their heart rate and made them breathe hard some of the time during the 7 days before the survey. ', '6');
INSERT INTO Question VALUES('', 'Diagnosed with Asthma', 'Students who were ever told by a doctor or nurse that they had asthma. ', '7');
INSERT INTO Question VALUES('', 'Have Asthma', 'Students who were ever told by a doctor or nurse that they had asthma and still have asthma. ', '7');